spring:
  datasource:
    driver-class-name:  com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yelp_db?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    #password: ''
    database: 0


#单节点
#server:
#  port: 8000
#spring:
#  application:
#    name: yelp-provider-usc                               # 指定注册到eureka server上的服务名称，对于用户服务中心
#eureka:
#  client:
#    service-url:
#      default-Zone: http://localhost:8761/eureka/,http://localhost:8762/eureka/         # 指定eureka server通信地址，注意/eureka/不能少
#    instance:
#      prefer-ip-address: true                             # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server

---


spring:
  application:
    name: yelp-bmc-server
---
spring:
  profiles: peer1                                 # 指定profile=peer1
server:
  port: 8001
eureka:
  instance:
    hostname: peer1                               # 指定当profile=peer1时，主机名是peer1
  client:
    service-url:
      default-Zone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
    instance:
      prefer-ip-address: true

---
spring:
  profiles: peer2
server:
  port: 8002
eureka:
  instance:
    hostname: peer2
  client:
    service-url:
      default-Zone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
    instance:
      prefer-ip-address: true



#java -jar yelp-bmc-server-0.0.1-SNAPSHOT.jar --spring.profiles.active=peer1
#java -jar yelp-bmc-server-0.0.1-SNAPSHOT.jar --spring.profiles.active=peer2
