

#-------Eureka Server 单节点服务-------------
#server:
#  port: 8761
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    register-with-eureka: false   #是否要注册到其他Eureka Server实例
#    fetch-registry: false         # 是否要从其他Eureka Server实例获取数据
#    service-url:
#      defaultZone: http://localhost:8761/eureka/




#-------Eureka Server 双节点集群-------------

#java -jar yelp-eureka-server-0.0.1-SNAPSHOT.jar --spring.profiles.active=peer1
#java -jar yelp-eureka-server-0.0.1-SNAPSHOT.jar --spring.profiles.active=peer2

#spring:
#  application:
#    name:
---
spring:
  profiles: peer1                                 #指定profile=peer1
  server:
    port: 8761
  eureka:
    instance:
      hostname: localhost                             #指定当profile=peer1时，主机名是peer1
    client:
      # Eureka服务注册中心会将自己作为客户端来尝试注册它自己，必須禁止
      register-with-eureka: false
      fetch-registry: false
      serviceUrl:
        defaultZone: http://peer2:8762/eureka/    #将自己注册到peer2这个Eureka上面去
---
spring:
  profiles: peer2                                 #指定profile=peer
  server:
    port: 8762
  eureka:
    instance:
      hostname: localhost                            #指定当profile=peer1时，主机名是peer1
    client:
      # Eureka服务注册中心会将自己作为客户端来尝试注册它自己，必須禁止
      register-with-eureka: false
      fetch-registry: false
      serviceUrl:
        defaultZone: http://peer1:8761/eureka/    #将自己注册到peer2这个Eureka上面去


