server:
  port: 8031
spring:
  application:
    name: yelp-hystrix-turbine
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
  instance:
    prefer-ip-address: true
turbine:
  appConfig: yelp-client-web-manage,yelp-client-web-mobile
  cluster-name-expression: "'default'"