server:
  port: 8080
spring:
  application:
    name: yelp-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/supernebula/yelpcloud-config.git
          username:
          password: